[package]
name = "fang_rs"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.4"
axum-template = "3.0.0"
handlebars = "6.3.2"
serde = "1.0.219"
serde_json = "1.0.142"
sqlx = "0.8.6"
tokio = { version = "1.47.1", features = ["full"] }
tower-http = { version = "0.5", features = ["fs"] }
